/*Generated by obj2c (Created by Noel Rojas Oliveras)*/
#include <libps.h>

#define LV0_COL_VERT_COUNT 8
#define LV0_COL_FACE_COUNT 4


/*Data generated*/
/*lv0_col_faces[]*/
/*lv0_col_vert[]*/
VECTOR lv0_col_faces[] = {
    {.vx=3, .vy=2, .vz=0},    {.vx=7, .vy=6, .vz=5},    {.vx=6, .vy=4, .vz=5},
    {.vx=1, .vy=3, .vz=0},
};



VECTOR lv0_col_vert[] = {
   {.vx=-573, .vy=0, .vz=-740},
   {.vx=-746, .vy=0, .vz=-565},
   {.vx=746, .vy=0, .vz=565},
   {.vx=573, .vy=0, .vz=740},
   {.vx=719, .vy=0, .vz=-719},
   {.vx=-719, .vy=0, .vz=-719},
   {.vx=719, .vy=0, .vz=719},
   {.vx=-719, .vy=0, .vz=719},
};


