/*Generated by obj2c (Created by Noel Rojas Oliveras)*/
#include <libps.h>

#define LV1_COL_VERT_COUNT 24
#define LV1_COL_FACE_COUNT 12


/*Data generated*/
/*lv1_col_faces[]*/
/*lv1_col_vert[]*/
VECTOR lv1_col_faces[] = {
    {.vx=1, .vy=3, .vz=2},    {.vx=5, .vy=7, .vz=6},    {.vx=9, .vy=11, .vz=10},
    {.vx=13, .vy=15, .vz=14},    {.vx=17, .vy=19, .vz=18},    {.vx=21, .vy=23, .vz=22},
    {.vx=0, .vy=1, .vz=2},    {.vx=4, .vy=5, .vz=6},    {.vx=8, .vy=9, .vz=10},
    {.vx=12, .vy=13, .vz=14},    {.vx=16, .vy=17, .vz=18},    {.vx=20, .vy=21, .vz=22},
};



VECTOR lv1_col_vert[] = {
   {.vx=-256, .vy=0, .vz=-1780},
   {.vx=256, .vy=0, .vz=-1780},
   {.vx=-256, .vy=0, .vz=1546},
   {.vx=256, .vy=0, .vz=1546},
   {.vx=519, .vy=0, .vz=543},
   {.vx=519, .vy=0, .vz=791},
   {.vx=6, .vy=0, .vz=543},
   {.vx=6, .vy=0, .vz=791},
   {.vx=265, .vy=0, .vz=-2271},
   {.vx=265, .vy=0, .vz=-1518},
   {.vx=-745, .vy=0, .vz=-2271},
   {.vx=-745, .vy=0, .vz=-1518},
   {.vx=26, .vy=0, .vz=-221},
   {.vx=26, .vy=0, .vz=27},
   {.vx=-488, .vy=0, .vz=-221},
   {.vx=-488, .vy=0, .vz=27},
   {.vx=523, .vy=0, .vz=-989},
   {.vx=523, .vy=0, .vz=-741},
   {.vx=10, .vy=0, .vz=-989},
   {.vx=10, .vy=0, .vz=-741},
   {.vx=768, .vy=0, .vz=1312},
   {.vx=768, .vy=0, .vz=1812},
   {.vx=-744, .vy=0, .vz=1312},
   {.vx=-744, .vy=0, .vz=1812},
};


