/*Generated by obj2c (Created by Noel Rojas Oliveras)*/
#include <libps.h>

#define LV2_COL_VERT_COUNT 16
#define LV2_COL_FACE_COUNT 16


/*Data generated*/
/*lv2_col_faces[]*/
/*lv2_col_vert[]*/
VECTOR lv2_col_faces[] = {
    {.vx=0, .vy=1, .vz=2},    {.vx=3, .vy=4, .vz=5},    {.vx=2, .vy=6, .vz=4},
    {.vx=2, .vy=7, .vz=8},    {.vx=5, .vy=6, .vz=9},    {.vx=10, .vy=3, .vz=11},
    {.vx=12, .vy=13, .vz=0},    {.vx=12, .vy=14, .vz=10},    {.vx=13, .vy=1, .vz=0},
    {.vx=14, .vy=4, .vz=3},    {.vx=8, .vy=6, .vz=2},    {.vx=1, .vy=7, .vz=2},
    {.vx=4, .vy=6, .vz=5},    {.vx=14, .vy=3, .vz=10},    {.vx=15, .vy=13, .vz=12},
    {.vx=0, .vy=14, .vz=12},
};



VECTOR lv2_col_vert[] = {
   {.vx=-256, .vy=0, .vz=0},
   {.vx=-1280, .vy=0, .vz=-768},
   {.vx=-1280, .vy=0, .vz=0},
   {.vx=-256, .vy=0, .vz=2048},
   {.vx=-1280, .vy=0, .vz=1280},
   {.vx=-1280, .vy=0, .vz=2048},
   {.vx=-2048, .vy=0, .vz=1280},
   {.vx=-2048, .vy=0, .vz=-768},
   {.vx=-2048, .vy=0, .vz=0},
   {.vx=-2048, .vy=0, .vz=2048},
   {.vx=1280, .vy=0, .vz=1280},
   {.vx=1280, .vy=0, .vz=2048},
   {.vx=1280, .vy=0, .vz=0},
   {.vx=-256, .vy=0, .vz=-768},
   {.vx=-256, .vy=0, .vz=1280},
   {.vx=1280, .vy=0, .vz=-768},
};


