/*Generated by obj2c (Created by Noel Rojas Oliveras)*/
#include <libps.h>

#define LV3_COL_VERT_COUNT 28
#define LV3_COL_FACE_COUNT 30


/*Data generated*/
/*lv3_col_faces[]*/
/*lv3_col_vert[]*/
VECTOR lv3_col_faces[] = {
    {.vx=0, .vy=1, .vz=2},    {.vx=3, .vy=4, .vz=5},    {.vx=5, .vy=6, .vz=3},
    {.vx=7, .vy=8, .vz=0},    {.vx=9, .vy=10, .vz=11},    {.vx=12, .vy=13, .vz=14},
    {.vx=12, .vy=10, .vz=15},    {.vx=4, .vy=16, .vz=17},    {.vx=16, .vy=15, .vz=9},
    {.vx=3, .vy=18, .vz=12},    {.vx=0, .vy=19, .vz=20},    {.vx=21, .vy=19, .vz=22},
    {.vx=23, .vy=7, .vz=24},    {.vx=25, .vy=20, .vz=21},    {.vx=23, .vy=25, .vz=26},
    {.vx=8, .vy=1, .vz=0},    {.vx=27, .vy=4, .vz=3},    {.vx=7, .vy=6, .vz=5},
    {.vx=5, .vy=8, .vz=7},    {.vx=15, .vy=10, .vz=9},    {.vx=18, .vy=13, .vz=12},
    {.vx=14, .vy=10, .vz=12},    {.vx=27, .vy=16, .vz=4},    {.vx=27, .vy=15, .vz=16},
    {.vx=6, .vy=18, .vz=3},    {.vx=2, .vy=19, .vz=0},    {.vx=20, .vy=19, .vz=21},
    {.vx=6, .vy=7, .vz=23},    {.vx=24, .vy=20, .vz=25},    {.vx=24, .vy=25, .vz=23},
};



VECTOR lv3_col_vert[] = {
   {.vx=-1536, .vy=0, .vz=256},
   {.vx=-2048, .vy=0, .vz=-256},
   {.vx=-2048, .vy=0, .vz=256},
   {.vx=512, .vy=0, .vz=-256},
   {.vx=-512, .vy=0, .vz=-1536},
   {.vx=-512, .vy=0, .vz=-256},
   {.vx=512, .vy=0, .vz=256},
   {.vx=-512, .vy=0, .vz=256},
   {.vx=-1536, .vy=0, .vz=-256},
   {.vx=1536, .vy=0, .vz=-2048},
   {.vx=2048, .vy=0, .vz=-1536},
   {.vx=2048, .vy=0, .vz=-2048},
   {.vx=1536, .vy=0, .vz=-256},
   {.vx=2048, .vy=0, .vz=256},
   {.vx=2048, .vy=0, .vz=-256},
   {.vx=1536, .vy=0, .vz=-1536},
   {.vx=512, .vy=0, .vz=-2048},
   {.vx=-512, .vy=0, .vz=-2048},
   {.vx=1536, .vy=0, .vz=256},
   {.vx=-2048, .vy=0, .vz=1536},
   {.vx=-1536, .vy=0, .vz=1536},
   {.vx=-1536, .vy=0, .vz=2048},
   {.vx=-2048, .vy=0, .vz=2048},
   {.vx=512, .vy=0, .vz=1536},
   {.vx=-512, .vy=0, .vz=1536},
   {.vx=-512, .vy=0, .vz=2048},
   {.vx=512, .vy=0, .vz=2048},
   {.vx=512, .vy=0, .vz=-1536},
};


