/*Generated by obj2c (Created by Noel Rojas Oliveras)*/
#include <libps.h>

#define LV4_COL_VERT_COUNT 28
#define LV4_COL_FACE_COUNT 28


/*Data generated*/
/*lv4_col_faces[]*/
/*lv4_col_vert[]*/
VECTOR lv4_col_faces[] = {
    {.vx=0, .vy=1, .vz=2},    {.vx=3, .vy=4, .vz=5},    {.vx=6, .vy=7, .vz=8},
    {.vx=9, .vy=10, .vz=11},    {.vx=12, .vy=8, .vz=10},    {.vx=13, .vy=14, .vz=15},
    {.vx=5, .vy=6, .vz=12},    {.vx=16, .vy=5, .vz=1},    {.vx=15, .vy=9, .vz=17},
    {.vx=18, .vy=19, .vz=20},    {.vx=14, .vy=13, .vz=21},    {.vx=6, .vy=22, .vz=23},
    {.vx=24, .vy=25, .vz=23},    {.vx=22, .vy=14, .vz=26},    {.vx=27, .vy=0, .vz=2},
    {.vx=16, .vy=3, .vz=5},    {.vx=12, .vy=6, .vz=8},    {.vx=17, .vy=9, .vz=11},
    {.vx=9, .vy=12, .vz=10},    {.vx=20, .vy=13, .vz=15},    {.vx=1, .vy=5, .vz=12},
    {.vx=0, .vy=16, .vz=1},    {.vx=18, .vy=15, .vz=17},    {.vx=15, .vy=18, .vz=20},
    {.vx=26, .vy=14, .vz=21},    {.vx=7, .vy=6, .vz=23},    {.vx=22, .vy=24, .vz=23},
    {.vx=24, .vy=22, .vz=26},
};



VECTOR lv4_col_vert[] = {
   {.vx=-512, .vy=0, .vz=-256},
   {.vx=512, .vy=0, .vz=-256},
   {.vx=512, .vy=0, .vz=-768},
   {.vx=-512, .vy=0, .vz=768},
   {.vx=512, .vy=0, .vz=768},
   {.vx=512, .vy=0, .vz=256},
   {.vx=1536, .vy=0, .vz=256},
   {.vx=2048, .vy=0, .vz=256},
   {.vx=2048, .vy=0, .vz=-256},
   {.vx=1536, .vy=0, .vz=-1536},
   {.vx=2048, .vy=0, .vz=-1536},
   {.vx=2048, .vy=0, .vz=-2048},
   {.vx=1536, .vy=0, .vz=-256},
   {.vx=-2048, .vy=0, .vz=1536},
   {.vx=-1536, .vy=0, .vz=1536},
   {.vx=-1536, .vy=0, .vz=-1536},
   {.vx=-512, .vy=0, .vz=256},
   {.vx=1536, .vy=0, .vz=-2048},
   {.vx=-1536, .vy=0, .vz=-2048},
   {.vx=-2048, .vy=0, .vz=-2048},
   {.vx=-2048, .vy=0, .vz=-1536},
   {.vx=-2048, .vy=0, .vz=2048},
   {.vx=1536, .vy=0, .vz=1536},
   {.vx=2048, .vy=0, .vz=1536},
   {.vx=1536, .vy=0, .vz=2048},
   {.vx=2048, .vy=0, .vz=2048},
   {.vx=-1536, .vy=0, .vz=2048},
   {.vx=-512, .vy=0, .vz=-768},
};


