/*Generated by obj2c (Created by Noel Rojas Oliveras)*/
#include <libps.h>

#define LV6_COL_VERT_COUNT 20
#define LV6_COL_FACE_COUNT 18


/*Data generated*/
/*lv6_col_faces[]*/
/*lv6_col_vert[]*/
VECTOR lv6_col_faces[] = {
    {.vx=1, .vy=3, .vz=0},    {.vx=5, .vy=0, .vz=4},    {.vx=2, .vy=7, .vz=3},
    {.vx=8, .vy=10, .vz=5},    {.vx=8, .vy=4, .vz=11},    {.vx=4, .vy=13, .vz=11},
    {.vx=14, .vy=1, .vz=15},    {.vx=17, .vy=11, .vz=16},    {.vx=0, .vy=18, .vz=19},
    {.vx=1, .vy=2, .vz=3},    {.vx=5, .vy=1, .vz=0},    {.vx=2, .vy=6, .vz=7},
    {.vx=8, .vy=9, .vz=10},    {.vx=8, .vy=5, .vz=4},    {.vx=4, .vy=12, .vz=13},
    {.vx=14, .vy=2, .vz=1},    {.vx=17, .vy=8, .vz=11},    {.vx=0, .vy=3, .vz=18},
};



VECTOR lv6_col_vert[] = {
   {.vx=257, .vy=0, .vz=768},
   {.vx=-255, .vy=0, .vz=768},
   {.vx=-255, .vy=0, .vz=1280},
   {.vx=257, .vy=0, .vz=1280},
   {.vx=257, .vy=0, .vz=-1280},
   {.vx=-255, .vy=0, .vz=-1280},
   {.vx=-255, .vy=0, .vz=1792},
   {.vx=257, .vy=0, .vz=1792},
   {.vx=-255, .vy=0, .vz=-1792},
   {.vx=-767, .vy=0, .vz=-1792},
   {.vx=-767, .vy=0, .vz=-1280},
   {.vx=257, .vy=0, .vz=-1792},
   {.vx=1281, .vy=0, .vz=-1280},
   {.vx=1281, .vy=0, .vz=-1792},
   {.vx=-767, .vy=0, .vz=1280},
   {.vx=-767, .vy=0, .vz=768},
   {.vx=257, .vy=0, .vz=-2304},
   {.vx=-255, .vy=0, .vz=-2304},
   {.vx=1281, .vy=0, .vz=1280},
   {.vx=1281, .vy=0, .vz=768},
};


