/*Generated by obj2c (Created by Noel Rojas Oliveras)*/
#include <libps.h>

#define LV7_COL_VERT_COUNT 36
#define LV7_COL_FACE_COUNT 34


/*Data generated*/
/*lv7_col_faces[]*/
/*lv7_col_vert[]*/
VECTOR lv7_col_faces[] = {
    {.vx=0, .vy=2, .vz=1},    {.vx=3, .vy=5, .vz=4},    {.vx=2, .vy=6, .vz=5},
    {.vx=5, .vy=8, .vz=7},    {.vx=9, .vy=11, .vz=10},    {.vx=0, .vy=12, .vz=9},
    {.vx=13, .vy=15, .vz=14},    {.vx=16, .vy=18, .vz=17},    {.vx=17, .vy=20, .vz=19},
    {.vx=19, .vy=22, .vz=21},    {.vx=10, .vy=24, .vz=23},    {.vx=25, .vy=26, .vz=13},
    {.vx=26, .vy=28, .vz=27},    {.vx=11, .vy=30, .vz=29},    {.vx=25, .vy=16, .vz=31},
    {.vx=32, .vy=1, .vz=16},    {.vx=17, .vy=34, .vz=33},    {.vx=35, .vy=2, .vz=0},
    {.vx=2, .vy=5, .vz=3},    {.vx=35, .vy=6, .vz=2},    {.vx=6, .vy=8, .vz=5},
    {.vx=12, .vy=11, .vz=9},    {.vx=32, .vy=12, .vz=0},    {.vx=26, .vy=15, .vz=13},
    {.vx=1, .vy=18, .vz=16},    {.vx=18, .vy=20, .vz=17},    {.vx=20, .vy=22, .vz=19},
    {.vx=11, .vy=24, .vz=10},    {.vx=31, .vy=26, .vz=25},    {.vx=31, .vy=28, .vz=26},
    {.vx=12, .vy=30, .vz=11},    {.vx=32, .vy=16, .vz=25},    {.vx=0, .vy=1, .vz=32},
    {.vx=19, .vy=34, .vz=17},
};



VECTOR lv7_col_vert[] = {
   {.vx=-256, .vy=0, .vz=256},
   {.vx=256, .vy=0, .vz=256},
   {.vx=256, .vy=0, .vz=768},
   {.vx=768, .vy=0, .vz=768},
   {.vx=768, .vy=0, .vz=1280},
   {.vx=256, .vy=0, .vz=1280},
   {.vx=-256, .vy=0, .vz=1280},
   {.vx=256, .vy=0, .vz=2048},
   {.vx=-256, .vy=0, .vz=2048},
   {.vx=-768, .vy=0, .vz=256},
   {.vx=-1280, .vy=0, .vz=256},
   {.vx=-1280, .vy=0, .vz=-256},
   {.vx=-768, .vy=0, .vz=-256},
   {.vx=-256, .vy=0, .vz=-1280},
   {.vx=-256, .vy=0, .vz=-2048},
   {.vx=256, .vy=0, .vz=-2048},
   {.vx=256, .vy=0, .vz=-256},
   {.vx=768, .vy=0, .vz=-256},
   {.vx=768, .vy=0, .vz=256},
   {.vx=1280, .vy=0, .vz=-256},
   {.vx=1280, .vy=0, .vz=256},
   {.vx=2048, .vy=0, .vz=-256},
   {.vx=2048, .vy=0, .vz=256},
   {.vx=-2048, .vy=0, .vz=256},
   {.vx=-2048, .vy=0, .vz=-256},
   {.vx=-256, .vy=0, .vz=-1024},
   {.vx=256, .vy=0, .vz=-1280},
   {.vx=512, .vy=0, .vz=-1280},
   {.vx=512, .vy=0, .vz=-1024},
   {.vx=-1280, .vy=0, .vz=-768},
   {.vx=-768, .vy=0, .vz=-768},
   {.vx=256, .vy=0, .vz=-1024},
   {.vx=-256, .vy=0, .vz=-256},
   {.vx=768, .vy=0, .vz=-768},
   {.vx=1280, .vy=0, .vz=-768},
   {.vx=-256, .vy=0, .vz=768},
};


